// Generated by gencpp from file ired_msgs/MotorSpeed.msg
// DO NOT EDIT!


#ifndef IRED_MSGS_MESSAGE_MOTORSPEED_H
#define IRED_MSGS_MESSAGE_MOTORSPEED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ired_msgs
{
template <class ContainerAllocator>
struct MotorSpeed_
{
  typedef MotorSpeed_<ContainerAllocator> Type;

  MotorSpeed_()
    : speed()  {
      speed.assign(0.0);
  }
  MotorSpeed_(const ContainerAllocator& _alloc)
    : speed()  {
  (void)_alloc;
      speed.assign(0.0);
  }



   typedef boost::array<double, 4>  _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::ired_msgs::MotorSpeed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ired_msgs::MotorSpeed_<ContainerAllocator> const> ConstPtr;

}; // struct MotorSpeed_

typedef ::ired_msgs::MotorSpeed_<std::allocator<void> > MotorSpeed;

typedef boost::shared_ptr< ::ired_msgs::MotorSpeed > MotorSpeedPtr;
typedef boost::shared_ptr< ::ired_msgs::MotorSpeed const> MotorSpeedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ired_msgs::MotorSpeed_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ired_msgs::MotorSpeed_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ired_msgs::MotorSpeed_<ContainerAllocator1> & lhs, const ::ired_msgs::MotorSpeed_<ContainerAllocator2> & rhs)
{
  return lhs.speed == rhs.speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ired_msgs::MotorSpeed_<ContainerAllocator1> & lhs, const ::ired_msgs::MotorSpeed_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ired_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ired_msgs::MotorSpeed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ired_msgs::MotorSpeed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ired_msgs::MotorSpeed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ired_msgs::MotorSpeed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ired_msgs::MotorSpeed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ired_msgs::MotorSpeed_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ired_msgs::MotorSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4c73c1913c2e2d9c04e814cd27a27b19";
  }

  static const char* value(const ::ired_msgs::MotorSpeed_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4c73c1913c2e2d9cULL;
  static const uint64_t static_value2 = 0x04e814cd27a27b19ULL;
};

template<class ContainerAllocator>
struct DataType< ::ired_msgs::MotorSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ired_msgs/MotorSpeed";
  }

  static const char* value(const ::ired_msgs::MotorSpeed_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ired_msgs::MotorSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[4] speed\n"
;
  }

  static const char* value(const ::ired_msgs::MotorSpeed_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ired_msgs::MotorSpeed_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorSpeed_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ired_msgs::MotorSpeed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ired_msgs::MotorSpeed_<ContainerAllocator>& v)
  {
    s << indent << "speed[]" << std::endl;
    for (size_t i = 0; i < v.speed.size(); ++i)
    {
      s << indent << "  speed[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.speed[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // IRED_MSGS_MESSAGE_MOTORSPEED_H
