// Generated by gencpp from file ired_msgs/PIDTuning.msg
// DO NOT EDIT!


#ifndef IRED_MSGS_MESSAGE_PIDTUNING_H
#define IRED_MSGS_MESSAGE_PIDTUNING_H

#include <ros/service_traits.h>


#include <ired_msgs/PIDTuningRequest.h>
#include <ired_msgs/PIDTuningResponse.h>


namespace ired_msgs
{

struct PIDTuning
{

typedef PIDTuningRequest Request;
typedef PIDTuningResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PIDTuning
} // namespace ired_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ired_msgs::PIDTuning > {
  static const char* value()
  {
    return "2067c5e03a8990aa0c4402e6f0d5da4b";
  }

  static const char* value(const ::ired_msgs::PIDTuning&) { return value(); }
};

template<>
struct DataType< ::ired_msgs::PIDTuning > {
  static const char* value()
  {
    return "ired_msgs/PIDTuning";
  }

  static const char* value(const ::ired_msgs::PIDTuning&) { return value(); }
};


// service_traits::MD5Sum< ::ired_msgs::PIDTuningRequest> should match
// service_traits::MD5Sum< ::ired_msgs::PIDTuning >
template<>
struct MD5Sum< ::ired_msgs::PIDTuningRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ired_msgs::PIDTuning >::value();
  }
  static const char* value(const ::ired_msgs::PIDTuningRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ired_msgs::PIDTuningRequest> should match
// service_traits::DataType< ::ired_msgs::PIDTuning >
template<>
struct DataType< ::ired_msgs::PIDTuningRequest>
{
  static const char* value()
  {
    return DataType< ::ired_msgs::PIDTuning >::value();
  }
  static const char* value(const ::ired_msgs::PIDTuningRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ired_msgs::PIDTuningResponse> should match
// service_traits::MD5Sum< ::ired_msgs::PIDTuning >
template<>
struct MD5Sum< ::ired_msgs::PIDTuningResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ired_msgs::PIDTuning >::value();
  }
  static const char* value(const ::ired_msgs::PIDTuningResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ired_msgs::PIDTuningResponse> should match
// service_traits::DataType< ::ired_msgs::PIDTuning >
template<>
struct DataType< ::ired_msgs::PIDTuningResponse>
{
  static const char* value()
  {
    return DataType< ::ired_msgs::PIDTuning >::value();
  }
  static const char* value(const ::ired_msgs::PIDTuningResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IRED_MSGS_MESSAGE_PIDTUNING_H
