// Generated by gencpp from file ired_msgs/PIDTuningResponse.msg
// DO NOT EDIT!


#ifndef IRED_MSGS_MESSAGE_PIDTUNINGRESPONSE_H
#define IRED_MSGS_MESSAGE_PIDTUNINGRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ired_msgs
{
template <class ContainerAllocator>
struct PIDTuningResponse_
{
  typedef PIDTuningResponse_<ContainerAllocator> Type;

  PIDTuningResponse_()
    : status(false)  {
    }
  PIDTuningResponse_(const ContainerAllocator& _alloc)
    : status(false)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::ired_msgs::PIDTuningResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ired_msgs::PIDTuningResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PIDTuningResponse_

typedef ::ired_msgs::PIDTuningResponse_<std::allocator<void> > PIDTuningResponse;

typedef boost::shared_ptr< ::ired_msgs::PIDTuningResponse > PIDTuningResponsePtr;
typedef boost::shared_ptr< ::ired_msgs::PIDTuningResponse const> PIDTuningResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ired_msgs::PIDTuningResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ired_msgs::PIDTuningResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ired_msgs::PIDTuningResponse_<ContainerAllocator1> & lhs, const ::ired_msgs::PIDTuningResponse_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ired_msgs::PIDTuningResponse_<ContainerAllocator1> & lhs, const ::ired_msgs::PIDTuningResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ired_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ired_msgs::PIDTuningResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ired_msgs::PIDTuningResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ired_msgs::PIDTuningResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ired_msgs::PIDTuningResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ired_msgs::PIDTuningResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ired_msgs::PIDTuningResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ired_msgs::PIDTuningResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a1255d4d998bd4d6585c64639b5ee9a";
  }

  static const char* value(const ::ired_msgs::PIDTuningResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a1255d4d998bd4dULL;
  static const uint64_t static_value2 = 0x6585c64639b5ee9aULL;
};

template<class ContainerAllocator>
struct DataType< ::ired_msgs::PIDTuningResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ired_msgs/PIDTuningResponse";
  }

  static const char* value(const ::ired_msgs::PIDTuningResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ired_msgs::PIDTuningResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool status\n"
;
  }

  static const char* value(const ::ired_msgs::PIDTuningResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ired_msgs::PIDTuningResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PIDTuningResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ired_msgs::PIDTuningResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ired_msgs::PIDTuningResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IRED_MSGS_MESSAGE_PIDTUNINGRESPONSE_H
