; Auto-generated. Do not edit!


(cl:in-package ired_msgs-msg)


;//! \htmlinclude MotorControl.msg.html

(cl:defclass <MotorControl> (roslisp-msg-protocol:ros-message)
  ((speed
    :reader speed
    :initarg :speed
    :type (cl:vector cl:float)
   :initform (cl:make-array 4 :element-type 'cl:float :initial-element 0.0))
   (pid_motor_front_left
    :reader pid_motor_front_left
    :initarg :pid_motor_front_left
    :type (cl:vector cl:float)
   :initform (cl:make-array 3 :element-type 'cl:float :initial-element 0.0))
   (pid_motor_front_right
    :reader pid_motor_front_right
    :initarg :pid_motor_front_right
    :type (cl:vector cl:float)
   :initform (cl:make-array 3 :element-type 'cl:float :initial-element 0.0))
   (pid_motor_rear_left
    :reader pid_motor_rear_left
    :initarg :pid_motor_rear_left
    :type (cl:vector cl:float)
   :initform (cl:make-array 3 :element-type 'cl:float :initial-element 0.0))
   (pid_motor_rear_right
    :reader pid_motor_rear_right
    :initarg :pid_motor_rear_right
    :type (cl:vector cl:float)
   :initform (cl:make-array 3 :element-type 'cl:float :initial-element 0.0)))
)

(cl:defclass MotorControl (<MotorControl>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MotorControl>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MotorControl)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ired_msgs-msg:<MotorControl> is deprecated: use ired_msgs-msg:MotorControl instead.")))

(cl:ensure-generic-function 'speed-val :lambda-list '(m))
(cl:defmethod speed-val ((m <MotorControl>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ired_msgs-msg:speed-val is deprecated.  Use ired_msgs-msg:speed instead.")
  (speed m))

(cl:ensure-generic-function 'pid_motor_front_left-val :lambda-list '(m))
(cl:defmethod pid_motor_front_left-val ((m <MotorControl>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ired_msgs-msg:pid_motor_front_left-val is deprecated.  Use ired_msgs-msg:pid_motor_front_left instead.")
  (pid_motor_front_left m))

(cl:ensure-generic-function 'pid_motor_front_right-val :lambda-list '(m))
(cl:defmethod pid_motor_front_right-val ((m <MotorControl>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ired_msgs-msg:pid_motor_front_right-val is deprecated.  Use ired_msgs-msg:pid_motor_front_right instead.")
  (pid_motor_front_right m))

(cl:ensure-generic-function 'pid_motor_rear_left-val :lambda-list '(m))
(cl:defmethod pid_motor_rear_left-val ((m <MotorControl>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ired_msgs-msg:pid_motor_rear_left-val is deprecated.  Use ired_msgs-msg:pid_motor_rear_left instead.")
  (pid_motor_rear_left m))

(cl:ensure-generic-function 'pid_motor_rear_right-val :lambda-list '(m))
(cl:defmethod pid_motor_rear_right-val ((m <MotorControl>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ired_msgs-msg:pid_motor_rear_right-val is deprecated.  Use ired_msgs-msg:pid_motor_rear_right instead.")
  (pid_motor_rear_right m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MotorControl>) ostream)
  "Serializes a message object of type '<MotorControl>"
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'speed))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'pid_motor_front_left))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'pid_motor_front_right))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'pid_motor_rear_left))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'pid_motor_rear_right))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MotorControl>) istream)
  "Deserializes a message object of type '<MotorControl>"
  (cl:setf (cl:slot-value msg 'speed) (cl:make-array 4))
  (cl:let ((vals (cl:slot-value msg 'speed)))
    (cl:dotimes (i 4)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits)))))
  (cl:setf (cl:slot-value msg 'pid_motor_front_left) (cl:make-array 3))
  (cl:let ((vals (cl:slot-value msg 'pid_motor_front_left)))
    (cl:dotimes (i 3)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits)))))
  (cl:setf (cl:slot-value msg 'pid_motor_front_right) (cl:make-array 3))
  (cl:let ((vals (cl:slot-value msg 'pid_motor_front_right)))
    (cl:dotimes (i 3)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits)))))
  (cl:setf (cl:slot-value msg 'pid_motor_rear_left) (cl:make-array 3))
  (cl:let ((vals (cl:slot-value msg 'pid_motor_rear_left)))
    (cl:dotimes (i 3)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits)))))
  (cl:setf (cl:slot-value msg 'pid_motor_rear_right) (cl:make-array 3))
  (cl:let ((vals (cl:slot-value msg 'pid_motor_rear_right)))
    (cl:dotimes (i 3)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MotorControl>)))
  "Returns string type for a message object of type '<MotorControl>"
  "ired_msgs/MotorControl")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MotorControl)))
  "Returns string type for a message object of type 'MotorControl"
  "ired_msgs/MotorControl")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MotorControl>)))
  "Returns md5sum for a message object of type '<MotorControl>"
  "05f5241cd8b6cd92a2aaba4f953638ba")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MotorControl)))
  "Returns md5sum for a message object of type 'MotorControl"
  "05f5241cd8b6cd92a2aaba4f953638ba")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MotorControl>)))
  "Returns full string definition for message of type '<MotorControl>"
  (cl:format cl:nil "float64[4] speed~%float64[3] pid_motor_front_left~%float64[3] pid_motor_front_right~%float64[3] pid_motor_rear_left~%float64[3] pid_motor_rear_right~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MotorControl)))
  "Returns full string definition for message of type 'MotorControl"
  (cl:format cl:nil "float64[4] speed~%float64[3] pid_motor_front_left~%float64[3] pid_motor_front_right~%float64[3] pid_motor_rear_left~%float64[3] pid_motor_rear_right~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MotorControl>))
  (cl:+ 0
     0 (cl:reduce #'cl:+ (cl:slot-value msg 'speed) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     0 (cl:reduce #'cl:+ (cl:slot-value msg 'pid_motor_front_left) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     0 (cl:reduce #'cl:+ (cl:slot-value msg 'pid_motor_front_right) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     0 (cl:reduce #'cl:+ (cl:slot-value msg 'pid_motor_rear_left) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     0 (cl:reduce #'cl:+ (cl:slot-value msg 'pid_motor_rear_right) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MotorControl>))
  "Converts a ROS message object to a list"
  (cl:list 'MotorControl
    (cl:cons ':speed (speed msg))
    (cl:cons ':pid_motor_front_left (pid_motor_front_left msg))
    (cl:cons ':pid_motor_front_right (pid_motor_front_right msg))
    (cl:cons ':pid_motor_rear_left (pid_motor_rear_left msg))
    (cl:cons ':pid_motor_rear_right (pid_motor_rear_right msg))
))
